### PR TITLE
Autogenerated api

### PR DESCRIPTION
**Pull request by bbartley**
This is a fairly complete alpha of the autogenerated API for OPIL.

It also reorganizes the directory structure in preparation for package distribution.

There is probably a lot that can be done to improve the organization and commenting the code.  But want to get a second pair of eyes on it.

### CODE REVIEW

**Review by RichM99 — COMMENTED** [review]
In opil_factory, lines 39-56, why is cardinality always set to 1? It can have any value. Here is a code snippet:

            for property_uri in associative_properties:
                property_name = Query.query_label(property_uri).replace(' ', '_')
                cardinality = Query.query_cardinality(property_uri, rdf_type)
                if len(cardinality):
                    upper_bound = 1
                else:
                    upper_bound = inf
                self.__dict__[property_name] = sbol.ReferencedObject(self, property_uri, 0, up

**Comment by bbartley** [comment]
Cardinality is not always set to `1`.  It is set to either `1` or `inf`.  In the latter case, the attribute is initialized to behave like a list.  Note that the `ReferencedObject` receives an `upper_bound` argument.  This is what sets the cardinality on the Python attribute

**Comment by rmarkelo** [comment]
Is this the correct interpretation of the code: If there is a cardinality restriction for a property on a class, then objects of that property are added to instances of that class one at a time, but if there is no cardinality restriction, objects of the property are added as a list?

-Rich


________________________________

**Review by RichM99 — APPROVED** [review]

**Comment by bbartley** [comment]
Yep, that's the correct interpretation.  Another way of stating it: If there is no cardinality restriction for a property on a class, then we implicitly assume it is unbounded.  I would prefer to state this explicitly rather than implicitly, but I don't know if that. can even be expressed in OWL.

**Pull request merged**
